"""add updated_by to tasks

Revision ID: b496f34709a9
Revises: 85417bce572b
Create Date: 2026-09-10 15:24:58.728727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b496f34709a9'
down_revision: Union[str, Sequence[str], None] = '85417bce572b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_updated_by'), 'tasks', ['updated_by'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_updated_by'), table_name='tasks')
    op.drop_column('tasks', 'updated_by')
    # ### end Alembic commands ###
